// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoD_Library_HCI_Core6.Models.Entities
{
    public partial class Autor
    {
        public Autor()
        {
            Knjiga = new HashSet<Knjiga>();
        }

        public uint Id { get; set; }
        public string ImePrezime { get; set; }

        public virtual ICollection<Knjiga> Knjiga { get; set; }
    }
}