// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoD_Library_HCI_Core6.Models.Entities
{
    public partial class Iznajmljuje
    {
        public uint Id { get; set; }
        public uint KnjigaId { get; set; }
        public uint NalogId { get; set; }
        public DateOnly DatumOd { get; set; }
        public DateOnly DatumDo { get; set; }
        public bool IsVracena { get; set; }

        public virtual Knjiga Knjiga { get; set; }
        public virtual Nalog Nalog { get; set; }
    }
}