// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoD_Library_HCI_Core6.Models.Entities
{
    public partial class Knjiga
    {
        public Knjiga()
        {
            Iznajmljuje = new HashSet<Iznajmljuje>();
            Autor = new HashSet<Autor>();
            Zanr = new HashSet<Zanr>();
        }

        public uint Id { get; set; }
        public string Naslov { get; set; }
        public uint GodinaIzdanja { get; set; }
        public string Opis { get; set; }
        public uint Kolicina { get; set; }
        public int DostupnaKolicina { get; set; }

        public virtual ICollection<Iznajmljuje> Iznajmljuje { get; set; }

        public virtual ICollection<Autor> Autor { get; set; }
        public virtual ICollection<Zanr> Zanr { get; set; }
    }
}